
language: php 
php:
  - 7.2
before_install: composer self-update
install: composer install --no-interaction
script: ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success: travis_retry ./vendor/bin/php-coveralls -v

before_deploy:
- openssl aes-256-cbc -k "$SUPER_SECRET_KEY_WORD" -in id_rsa.enc -out /tmp/id_rsa
  -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa
- ssh-add /tmp/id_rsa
- ssh-keyscan $DEPLOYMENT_HOST_IP >> ~/.ssh/known_hosts
- echo  -e "
    APP_NAME=Laravel \n
    APP_ENV=local \n
    APP_KEY=$APP_KEY \n
    APP_DEBUG=true \n
    APP_URL=http://localhost \n
    LOG_CHANNEL=stack \n
    DB_CONNECTION=$DB_CONNECTION \n
    DB_HOST=$DB_HOST \n
    DB_PORT=$DB_PORT \n
    DB_DATABASE=$DB_DATABASE \n
    DB_USERNAME=$DB_USERNAME \n
    DB_PASSWORD=$DB_PASSWORD \n
    BROADCAST_DRIVER=log \n
    CACHE_DRIVER=file \n
    SESSION_DRIVER=file \n
    SESSION_LIFETIME=120 \n
    QUEUE_DRIVER=sync \n
    REDIS_HOST=127.0.0.1 \n
    REDIS_PASSWORD=null \n
    REDIS_PORT=6379 \n
    MAIL_DRIVER=$MAIL_DRIVER \n
    MAIL_HOST=$MAIL_HOST \n
    MAIL_PORT=$MAIL_PORT \n
    MAIL_USERNAME=$MAIL_USERNAME \n
    MAIL_PASSWORD=$MAIL_PASSWORD \n
    MAIL_ENCRYPTION=null \n
    PUSHER_APP_ID= \n
    PUSHER_APP_KEY= \n
    PUSHER_APP_SECRET= \n
    PUSHER_APP_CLUSTER=mt1 \n
    MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}" \n
    MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"\n
  " > $TRAVIS_BUILD_DIR/.env
- rsync -r $TRAVIS_BUILD_DIR ubuntu@"$DEPLOYMENT_HOST_IP":~/tmp

deploy:
  - provider: script
    skip_cleanup: true
    script: ssh ubuntu@"$DEPLOYMENT_HOST_IP" "cd ~/tmp/Miscsite;sudo docker-compose up -d --no-deps --build app nginx;"
    on:
      branch: master
